sudo: required

language: generic

services:
  - docker

env:
  global:
    - PROJECT_NAME=ansible
    - ANSIBLE_VERSION=2.4.3.0
    - PYTHON_VERSION=2.7.14
    - DOCKER_IMAGE_NAME=$DOCKER_USER/$PROJECT_NAME

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

matrix:
  include:
    - env:
        - VARIANT=.
        - DOCKER_IMAGE_VERSION_FULL=${ANSIBLE_VERSION}-python${PYTHON_VERSION}
        - DOCKER_IMAGE_VERSION_SIMPLE=${ANSIBLE_VERSION}
    - env:
        - VARIANT=aws
        - DOCKER_IMAGE_VERSION_FULL=${ANSIBLE_VERSION}-${VARIANT}-python${PYTHON_VERSION}
        - DOCKER_IMAGE_VERSION_SIMPLE=${VARIANT}
    - env:
        - VARIANT=azure
        - DOCKER_IMAGE_VERSION_FULL=${ANSIBLE_VERSION}-${VARIANT}-python${PYTHON_VERSION}
        - DOCKER_IMAGE_VERSION_SIMPLE=${VARIANT}

script:
  # build Docker image
  - |
    docker build \
      --build-arg ANSIBLE_VERSION=${ANSIBLE_VERSION} \
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
      -t ${DOCKER_IMAGE_NAME}:test \
      ${VARIANT}
  # run tests
  - DOCKER_IMAGE_VERSION_NAME=${DOCKER_IMAGE_NAME}:test ./tests/check.sh
  # push Docker image
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
  - docker tag ${DOCKER_IMAGE_NAME}:test ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION_FULL}
  - docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION_FULL}
  - docker tag ${DOCKER_IMAGE_NAME}:test ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION_SIMPLE}
  - docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION_SIMPLE}
